version: "3"
services:
  redis:
    image: "redis:4"
  uraiden:
    build: 
      context: .
      dockerfile: uraiden.Dockerfile
    command: '-m server --private-key key --private-key-password-file password --rpc-provider http://118.31.18.101:4045 start'
  dbot:
    build: 
      context: .
      dockerfile: dbot.Dockerfile
    depends_on: 
      - redis
      - uraiden
    links:
      - redis
      - uraiden
    ports:
      - "3000:3000"
    

